<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ldndwm406292" name="Default test" tests="7" failures="1" timestamp="14 Aug 2015 19:02:24 GMT" time="0.11" errors="0">
  <testcase name="straightforword" time="0.094" classname="com.net.testng.protocol.TestCurrencyEvent"/>
  <testcase name="straightforwordOutOfTime" time="0.0" classname="com.net.testng.protocol.TestCurrencyEvent">
    <failure type="java.lang.AssertionError" message="expected [OUT_OF_TIME] but found [WAITING]">
      <![CDATA[java.lang.AssertionError: expected [OUT_OF_TIME] but found [WAITING]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at com.net.testng.protocol.TestCurrencyEvent.straightforwordOutOfTime(TestCurrencyEvent.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- straightforwordOutOfTime -->
  <testcase name="straightforwordTestLong" time="0.0" classname="com.net.testng.protocol.TestCurrencyEvent"/>
  <testcase name="straightforwordTestShort" time="0.0" classname="com.net.testng.protocol.TestCurrencyEvent"/>
  <testcase name="twoFieldPerNewsTestLongPlusEventAlreadyEvaluatedTest" time="0.0" classname="com.net.testng.protocol.TestCurrencyEvent"/>
  <testcase name="twoFieldPerTwoNewsTestLongPlusEventAlreadyEvaluatedTest" time="0.0" classname="com.net.testng.protocol.TestCurrencyEvent"/>
  <testcase name="twoNewsPerEventTestShort" time="0.0" classname="com.net.testng.protocol.TestCurrencyEvent"/>
</testsuite> <!-- Default test -->
